language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to run tests
# command to install dependencies
install:
  - pip install -r requirements_prod.txt
script:
  - python preprocessing/clean_spaces.py
