language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements_prod.txt
  - sudo apt-get install libenchant1c2a
before_script:
  - curl -o embed/glove/glove.twitter.27B.25d.txt https://srv-file7.gofile.io/downloadStore/srv-store2/m4DyZ8/glove.twitter.27B.25d.txt
# TODO ...
script:
  - python -c "exec(\"import sys\nsys.path.append('./preprocessing')\nfrom pipeline_mmst import PipelineMMST\na = PipelineMMST()\")"
